/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flight.simulator.interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author blakejoynes
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewEditUsers = new javax.swing.JButton();
        viewEditLessons = new javax.swing.JButton();
        viewEditGoals = new javax.swing.JButton();
        logOUt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        viewEditUsers.setText("User Options");
        viewEditUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEditUsersMouseClicked(evt);
            }
        });
        viewEditUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditUsersActionPerformed(evt);
            }
        });

        viewEditLessons.setText("Lesson Options");
        viewEditLessons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEditLessonsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewEditLessonsMouseEntered(evt);
            }
        });
        viewEditLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditLessonsActionPerformed(evt);
            }
        });

        viewEditGoals.setText("Goal Options");
        viewEditGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditGoalsActionPerformed(evt);
            }
        });

        logOUt.setText("Log Out");
        logOUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOUtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewEditLessons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewEditUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewEditGoals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOUt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewEditUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewEditLessons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewEditGoals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(logOUt)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEditLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditLessonsActionPerformed
        
    }//GEN-LAST:event_viewEditLessonsActionPerformed

    private void viewEditGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditGoalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEditGoalsActionPerformed

    private void logOUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOUtMouseClicked
      JOptionPane.showMessageDialog(null, "You are now logging out!");
      this.dispose();
    }//GEN-LAST:event_logOUtMouseClicked

    private void viewEditUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditUsersActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewEditUser().setVisible(true);
            }
        });
    }//GEN-LAST:event_viewEditUsersActionPerformed

    private void viewEditUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEditUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEditUsersMouseClicked

    private void viewEditLessonsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEditLessonsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEditLessonsMouseEntered

    private void viewEditLessonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEditLessonsMouseClicked
        new viewEditLessons().setVisible(true);
    }//GEN-LAST:event_viewEditLessonsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logOUt;
    private javax.swing.JButton viewEditGoals;
    private javax.swing.JButton viewEditLessons;
    private javax.swing.JButton viewEditUsers;
    // End of variables declaration//GEN-END:variables
}
